version: "3.8"
services:
    client:
        image: cb-client
        build: ./client
        ports:
            - "80:80"
    server:
        image: cb-server
        build: ./server
        ports:
            - "8080:8080"
